baseURL: "http://alexandmanu.com"
languageCode: "en-us"
title: "alex and manu"
theme: archie

services:
  disqus:
    shortname: alexandmanu


taxonomies:
  author: authors
  tag: tags
  category: categories

params:
  mode: "auto" 