baseURL: "http://alexandmanu.com"
languageCode: "en-us"
title: "alex and manu"
theme: hugo-bearblog

services:
  disqus:
    shortname: alexandmanu


taxonomies:
  author: authors
  tag: tags
  category: categories